services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      # Optional: Persist Metabase config if using a custom one
      - metabase-data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: web_honeypot
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: admin
      MB_DB_HOST: postgres
    networks:
      - metanet1
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    build: ./postgres
    image: postgres:17
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: web_honeypot
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - metanet1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  metanet1:
    driver: bridge

volumes:
  pgdata:
    name: metabase_pgdata
  metabase-data:
    name: metabase_data
